package catalog

import "fmt"

// Interest identifies an individual interest. The underlying string
// is the display label; the wire format is derived (lowercase,
// spaces to underscores).
//
//nolint:recvcheck // MarshalText requires value receiver, UnmarshalText requires pointer
type Interest string

// Label returns the human-readable label.
func (i Interest) Label() string { return string(i) }

// String returns the wire format.
func (i Interest) String() string { return toWire(string(i)) }

// MarshalText implements encoding.TextMarshaler.
func (i Interest) MarshalText() ([]byte, error) {
	if !interestSet[i] {
		return nil, fmt.Errorf("invalid interest: %q", i)
	}
	return []byte(i.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (i *Interest) UnmarshalText(text []byte) error {
	parsed, ok := interestLookup[string(text)]
	if !ok {
		return fmt.Errorf("unknown interest: %q", text)
	}
	*i = parsed
	return nil
}

// AllInterests returns all interest values sorted by label.
func AllInterests() []Interest { return interests }

// interests is the canonical list. Keep sorted by label.
var interests = []Interest{
	"3+ Penetration",
	"Age Differences",
	"Age Progression",
	"Age Regression",
	"All the Way Through",
	"Anal Vore",
	"Anal",
	"Androgyny",
	"Animal Transformation",
	"Aphrodisiacs",
	"Ass to Mouth",
	"Ass Worship",
	"Auto-Fellatio",
	"Barbed Cocks",
	"Begging",
	"Belly Fucking",
	"Bimbofication",
	"Birthing",
	"Biting",
	"Blood",
	"Bloodplay",
	"Body Swapping",
	"Body Writing",
	"Bondage",
	"Branding",
	"Breeding",
	"Bukkake",
	"Caging",
	"Cervical Penetration",
	"Chastity",
	"Choking",
	"Chubby",
	"Clit Play",
	"CNC",
	"Cock Vore",
	"Condoms",
	"Corruption",
	"Creampie",
	"Crossdressing",
	"Crotch Sniffing",
	"Cum Bath",
	"Cum Enemas",
	"Cum",
	"Cuntboys",
	"Deepthroat",
	"Degradation",
	"Diapers",
	"Digestion",
	"Dirty Talking",
	"Docking",
	"Double Penetration",
	"Drug / Alcohol Use",
	"Ear Play",
	"Electric Toys",
	"Enemas",
	"Excessive Cum",
	"Exhibitionism",
	"Exotic Cocks",
	"Face Fucking",
	"Face Sitting",
	"Farting",
	"Felching",
	"Fellatio",
	"Femboys",
	"Femininity",
	"Feminization",
	"Feral",
	"Fisting",
	"Flexibility",
	"Food Play",
	"Foot Play",
	"Foreplay",
	"Foreskin Worship",
	"Frotting",
	"Gags",
	"Gangbangs",
	"Gender Transformation",
	"Glory Hole",
	"Group Sex",
	"Growth",
	"Hair Pulling",
	"Hand Cuffs",
	"Handjob / Fingering",
	"Hard Vore",
	"Horns",
	"Hotdogging",
	"Humiliation",
	"Hyper Asses",
	"Hyper Balls",
	"Hyper Breasts",
	"Hyper Cocks",
	"Hyper Fat",
	"Hyper Muscle",
	"Hyper Vaginas",
	"Hyper",
	"Hyper-Voluptuous",
	"Ice",
	"In Heat",
	"Incest",
	"Inflation",
	"Kissing",
	"Knotted Cocks",
	"Knotting",
	"Lactation",
	"Leash & Collar",
	"Licking",
	"Living Insertions",
	"Macrophilia",
	"Magic Users",
	"Male Pregnancy",
	"Masculinity",
	"Masturbation",
	"Messy",
	"Microphilia",
	"Mind Control",
	"Multiple Orgasms",
	"Musk",
	"Natural Musk",
	"Navel Play",
	"Nipple Penetration",
	"Nipple Piercings",
	"Nursing",
	"Objectification",
	"Objectophilia",
	"Oral Fixation",
	"Orgasm Control",
	"Oviposition",
	"Pain",
	"Paw Play",
	"Pegging",
	"Pet / Master",
	"Piercings",
	"Powerbottoming",
	"Pregnancy",
	"Prolapse",
	"Prostate Play",
	"Prostitution",
	"Public Humiliation",
	"Queefing",
	"Rimming",
	"Rubber / Elastic / Latex",
	"Saliva",
	"Scat",
	"Scissoring",
	"Scratching",
	"Sex Toys",
	"Sexual Frustration",
	"Shaving",
	"Sheath Play",
	"Shrinking",
	"Size Difference",
	"Slapping",
	"Slime",
	"Sloppy Seconds",
	"Small Breasts",
	"Smoking",
	"Snowballing",
	"Soft Vore",
	"Somnophilia",
	"Sounding",
	"Spanking",
	"Squirting",
	"Stomach Bulging",
	"Strap-ons",
	"Strip Tease",
	"Stuckage",
	"Swallowing",
	"Sweat",
	"Tail Pulling",
	"Tail Sex",
	"Tailsex",
	"Teasing",
	"Teeth Play",
	"Tentacles",
	"Throat Penetration",
	"Tickling",
	"Titfucking",
	"Tomboys",
	"Transformation",
	"Twinks",
	"Twins",
	"Udders",
	"Unusual Semen",
	"Urethra Play",
	"Vanilla Sex",
	"Virgin",
	"Vorarephilia",
	"Voyeurism",
	"Watersports",
	"Wax Play",
	"Whipping",
}

var interestSet = buildSet(interests)
var interestLookup = buildLookup(interests)
