package match

import (
	"context"
	"sync/atomic"
	"time"
)

const (
	// DefaultMatchTimeout is how long a user waits before the
	// matcher relaxes interest scoring requirements.
	DefaultMatchTimeout = 10 * time.Second

	// matchTickInterval is how often the matcher re-runs its
	// matching pass.
	matchTickInterval = 1 * time.Second

	queueBufSize = 256
)

// Entry is a user waiting in the match queue.
type Entry struct {
	Token   Token
	Profile *Profile
	Queued  time.Time

	// Attempt is a unique ID for this queue entry, generated by
	// Enqueue. The hub uses it to detect stale match results: if
	// a client leaves or re-queues between being matched and the
	// result being processed, the attempt IDs will differ and the
	// match is discarded.
	Attempt Token
}

// ResultEntry identifies one side of a match result.
type ResultEntry struct {
	Token   Token
	Attempt Token
}

// Result is a pair of matched users.
type Result struct {
	A, B ResultEntry
}

// Matcher manages the matchmaking queue and runs a scoring loop
// to pair compatible users.
type Matcher struct {
	find    chan *Entry
	leave   chan Token
	matched chan Result
	timeout time.Duration
	queue   []*Entry
	running atomic.Bool
}

// NewMatcher creates a Matcher with the given match timeout.
func NewMatcher(timeout time.Duration) *Matcher {
	return &Matcher{
		find:    make(chan *Entry, queueBufSize),
		leave:   make(chan Token, queueBufSize),
		matched: make(chan Result, queueBufSize),
		timeout: timeout,
	}
}

// Enqueue adds a user to the match queue and returns an attempt
// ID that can be used to verify the result in handleMatched.
// Blocks until the entry is accepted or the context is cancelled.
func (m *Matcher) Enqueue(ctx context.Context, token Token, profile *Profile) Token {
	attempt := NewToken()
	select {
	case m.find <- &Entry{
		Token:   token,
		Attempt: attempt,
		Profile: profile,
		Queued:  time.Now(),
	}:
		return attempt
	case <-ctx.Done():
		return ""
	}
}

// Leave removes a client (by token) from the match queue. Blocks
// until the request is accepted or the context is cancelled.
func (m *Matcher) Leave(ctx context.Context, token Token) {
	select {
	case m.leave <- token:
	case <-ctx.Done():
	}
}

// Matched returns the channel that emits match results.
func (m *Matcher) Matched() <-chan Result {
	return m.matched
}

// Run processes the queue until ctx is cancelled. It must be
// called exactly once; subsequent calls are no-ops.
func (m *Matcher) Run(ctx context.Context) {
	if !m.running.CompareAndSwap(false, true) {
		return
	}
	ticker := time.NewTicker(matchTickInterval)
	defer ticker.Stop()

	for {
		select {
		case entry := <-m.find:
			m.removeByToken(entry.Token)
			m.queue = append(m.queue, entry)
			m.matchPass(ctx)

		case token := <-m.leave:
			m.removeByToken(token)

		case <-ticker.C:
			m.matchPass(ctx)

		case <-ctx.Done():
			return
		}
	}
}

// matchPass runs a greedy best-pair matching pass over the queue.
//
// On each iteration it evaluates every pair in the queue and
// selects the one with the highest compatibility score. The
// winning pair is removed from the queue and sent as a Result
// on the matched channel. The loop repeats until no viable pair
// remains or the context is cancelled.
//
// Scoring rules:
//   - Incompatible pairs (filter mismatch, blocked, excluded
//     interests) are skipped entirely via Compatible.
//   - Compatible pairs are scored by weighted Jaccard similarity
//     on interests. A positive score is required for a match.
//   - If either entry has waited longer than m.timeout, the
//     score threshold is relaxed to zero so compatible users
//     with disjoint (or no) interests can still match.
//
// This is O(n^2) per pass and runs synchronously in the Run
// goroutine. Acceptable for small queues; will need optimization
// if queue sizes grow significantly.
func (m *Matcher) matchPass(ctx context.Context) {
	for {
		bestI, bestJ, bestScore := -1, -1, -1.0
		now := time.Now()

		// evaluate all pairs to find the highest-scoring
		// compatible match
		for idx := range len(m.queue) - 1 {
			entryA := m.queue[idx]
			for jdx := idx + 1; jdx < len(m.queue); jdx++ {
				entryB := m.queue[jdx]

				// hard filter: gender, role, interests,
				// blocks
				if !Compatible(entryA.Profile, entryB.Profile, entryA.Token, entryB.Token) {
					continue
				}

				score := Score(entryA.Profile, entryB.Profile)
				timedOut := now.Sub(entryA.Queued) >= m.timeout ||
					now.Sub(entryB.Queued) >= m.timeout

				// require a positive interest overlap unless
				// one side has waited past the timeout, in
				// which case any compatible pair is accepted
				if score <= 0 && !timedOut {
					continue
				}

				if score > bestScore {
					bestI, bestJ, bestScore = idx, jdx, score
				}
			}
		}

		// no viable pair found; done for this pass
		if bestI < 0 {
			return
		}

		result := Result{
			A: ResultEntry{Token: m.queue[bestI].Token, Attempt: m.queue[bestI].Attempt},
			B: ResultEntry{Token: m.queue[bestJ].Token, Attempt: m.queue[bestJ].Attempt},
		}

		// remove matched pair from the queue. higher index
		// first so the lower index stays valid.
		m.queue = append(m.queue[:bestJ], m.queue[bestJ+1:]...)
		m.queue = append(m.queue[:bestI], m.queue[bestI+1:]...)

		// send result to the hub. if the context is cancelled
		// (shutdown), bail out instead of blocking.
		select {
		case m.matched <- result:
		case <-ctx.Done():
			return
		}
	}
}

func (m *Matcher) removeByToken(token Token) {
	for idx, entry := range m.queue {
		if entry.Token == token {
			m.queue = append(m.queue[:idx], m.queue[idx+1:]...)
			return
		}
	}
}
